# Generated by Django 6.0.3 on 2026-03-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_loan_interest_percent_loan_due_date_and_more'),
        ('members', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('loan', 'amount', 'date'), name='unique_payment_per_loan_date_amount'),
        ),
    ]
