# Generated by Django 5.0.14 on 2026-03-24 22:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0005_alter_member_date_joined'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_value', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Price per share (KES)', max_digits=10)),
                ('min_shares', models.PositiveIntegerField(default=1, help_text='Minimum shares a member must hold to remain in good standing')),
                ('max_shares', models.PositiveIntegerField(blank=True, help_text='Maximum shares any one member can hold (leave blank for no limit)', null=True)),
                ('loan_multiplier', models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Max loan = share value × this multiplier (used by loan products with shares basis)', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Share Configuration',
            },
        ),
        migrations.CreateModel(
            name='ShareAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares_held', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_account', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='ShareTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Share Purchase'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('refund', 'Share Refund (Exit)'), ('bonus', 'Bonus Shares'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('shares', models.PositiveIntegerField(help_text='Number of shares in this transaction')),
                ('amount', models.DecimalField(decimal_places=2, help_text='KES value of this transaction', max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='M-Pesa code, cheque no., etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shares.shareaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
