# Generated by Django 4.2.30 on 2026-05-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_shareconfig_chama'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharetransaction',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
