# Generated by Django 5.0.14 on 2026-03-30 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('investment_type', models.CharField(choices=[('property', 'Property / Real Estate'), ('stock', 'Stocks / Shares'), ('business', 'Business Venture'), ('bond', 'Bond / Fixed Deposit'), ('sacco', 'SACCO / Co-operative'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('exited', 'Exited / Sold'), ('written_off', 'Written Off')], default='active', max_length=20)),
                ('amount_invested', models.DecimalField(decimal_places=2, help_text='Total capital put into this investment', max_digits=14)),
                ('date_invested', models.DateField()),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current estimated market value', max_digits=14, null=True)),
                ('valuation_date', models.DateField(blank=True, null=True)),
                ('exit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('exit_notes', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text='Physical address, exchange, or institution', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_invested'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='investment_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='investments.investment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_docs_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('injection', 'Capital Injection'), ('income', 'Income / Returns'), ('dividend', 'Dividend'), ('exit', 'Exit / Sale Proceeds'), ('expense', 'Investment Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, help_text='Receipt, M-Pesa code, bank ref, etc.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investment')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
