# Generated by Django 6.0.2 on 2026-03-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contribution',
            name='void_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
