# Generated by Django 5.0.14 on 2026-03-30 22:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0005_alter_member_date_joined'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WelfareSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_contribution', models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='Default amount each member contributes per event/period', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Welfare Settings',
                'verbose_name_plural': 'Welfare Settings',
            },
        ),
        migrations.CreateModel(
            name='WelfareClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('hospital', 'Hospitalisation'), ('funeral', 'Funeral / Bereavement'), ('maternity', 'Maternity'), ('disability', 'Disability'), ('other', 'Other')], max_length=20)),
                ('beneficiary_name', models.CharField(blank=True, help_text='Name of the person the claim is for (leave blank if same as member)', max_length=200)),
                ('beneficiary_relation', models.CharField(blank=True, help_text='e.g. Self, Spouse, Child, Parent', max_length=100)),
                ('description', models.TextField(help_text='Brief description of the event/need')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_disbursed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('date_filed', models.DateField(auto_now_add=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('date_disbursed', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='welfare_docs/')),
                ('rejection_reason', models.TextField(blank=True)),
                ('disbursement_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer')], max_length=20)),
                ('disbursement_ref', models.CharField(blank=True, help_text='M-Pesa code, cheque number, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welfare_claims_disbursed', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welfare_claims', to='members.member')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welfare_claims_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_filed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WelfareContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='M-Pesa code or receipt number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='welfare.welfareclaim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welfare_contributions_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welfare_contributions', to='members.member')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
