# Generated by Django 5.0.14 on 2026-03-31 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('welfare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welfareclaim',
            name='chama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welfare_claims', to='tenants.chama'),
        ),
        migrations.AddField(
            model_name='welfaresettings',
            name='chama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welfare_settings', to='tenants.chama'),
        ),
    ]
