# Generated by Django 4.2.13 on 2026-06-20 19:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0002_welfareclaim_chama_welfaresettings_chama'),
    ]

    operations = [
        migrations.AddField(
            model_name='welfaresettings',
            name='rate_disability',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contribution per member for Disability claims', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='welfaresettings',
            name='rate_funeral',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contribution per member for Funeral / Bereavement claims', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='welfaresettings',
            name='rate_hospital',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contribution per member for Hospitalisation claims', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='welfaresettings',
            name='rate_maternity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contribution per member for Maternity claims', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='welfaresettings',
            name='rate_other',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contribution per member for Other claims', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='welfaresettings',
            name='standard_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='Default amount each member contributes per event (used if no per-type rate is set)', max_digits=10),
        ),
    ]
