# Generated by Django 5.0.14 on 2026-03-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the chama, e.g. "Nairobi Women Investment Group"', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='Subdomain identifier, e.g. "nairobi-wig" → nairobi-wig.yourdomain.com', max_length=80, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Short description shown on the login page', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='chama_logos/')),
                ('primary_color', models.CharField(default='#2563eb', help_text='Hex colour for branding, e.g. #2563eb', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive chamas cannot log in')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chama',
                'verbose_name_plural': 'Chamas',
                'ordering': ['name'],
            },
        ),
    ]
