# Generated by Django 4.2.30 on 2026-04-24 21:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_assign_default_chama'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='months_paid',
            field=models.PositiveIntegerField(default=0, help_text='Total months of paid subscription recorded'),
        ),
        migrations.AddField(
            model_name='chama',
            name='plan',
            field=models.CharField(choices=[('free', 'Starter (Free)'), ('growth', 'Growth — KES 999/mo'), ('enterprise', 'Enterprise — Custom')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='chama',
            name='plan_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly subscription amount (KES). Auto-set from plan, override for enterprise.', max_digits=10),
        ),
        migrations.AddField(
            model_name='chama',
            name='subscription_end',
            field=models.DateField(blank=True, help_text='Date the current subscription period ends (null = active)', null=True),
        ),
        migrations.AddField(
            model_name='chama',
            name='subscription_start',
            field=models.DateField(blank=True, help_text='Date the paid subscription started', null=True),
        ),
        migrations.AddField(
            model_name='chama',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative subscription revenue collected from this chama', max_digits=12),
        ),
    ]
