# Generated by Django 4.2.30 on 2026-04-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_subscription_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='trial_ends',
            field=models.DateField(blank=True, help_text='Date the free trial expires. Auto-set to 30 days from registration.', null=True),
        ),
        migrations.AlterField(
            model_name='chama',
            name='plan',
            field=models.CharField(choices=[('free', 'Free Trial (30 days)'), ('basic', 'Basic — KES 500/mo'), ('standard', 'Standard — KES 999/mo'), ('enterprise', 'Enterprise — Custom')], default='free', max_length=20),
        ),
    ]
