# Generated by Django 5.0.14 on 2026-03-30 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0005_alter_member_date_joined'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AGM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. 2025 Annual General Meeting', max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('open', 'Open / In Progress'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('quorum', models.PositiveIntegerField(default=0, help_text='Minimum members required for valid meeting (0 = no quorum check)')),
                ('notice', models.TextField(blank=True, help_text='Official notice / invitation text sent to members')),
                ('minutes', models.TextField(blank=True, help_text='Full meeting minutes recorded during/after the AGM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agms_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AGM',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('item_type', models.CharField(choices=[('discussion', 'Discussion'), ('resolution', 'Resolution / Motion'), ('election', 'Election'), ('report', 'Report Presentation')], default='discussion', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('presenter', models.CharField(blank=True, help_text='Name of person presenting this item', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Notes recorded during discussion')),
                ('is_done', models.BooleanField(default=False)),
                ('agm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='agm.agm')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('motion_text', models.TextField(help_text='The exact wording of the motion put to vote')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('voting', 'Voting Open'), ('passed', 'Passed'), ('failed', 'Failed'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('anonymous_voting', models.BooleanField(default=False, help_text='If enabled, individual votes are hidden from non-admins')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agenda_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution', to='agm.agendaitem')),
                ('agm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='agm.agm')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions_proposed', to='members.member')),
                ('seconded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions_seconded', to='members.member')),
            ],
            options={
                'ordering': ['agm', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AGMAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('represented_by', models.CharField(blank=True, help_text='Name of proxy if member is represented', max_length=200)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('agm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='agm.agm')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agm_attendances', to='members.member')),
            ],
            options={
                'ordering': ['member__name'],
                'unique_together': {('agm', 'member')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('abstain', 'Abstain')], max_length=10)),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agm_votes', to='members.member')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='agm.resolution')),
            ],
            options={
                'unique_together': {('resolution', 'member')},
            },
        ),
    ]
