# Generated by Django 5.0.14 on 2026-03-24 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('members', '0005_alter_member_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_user', to='members.member'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('treasurer', 'Treasurer'), ('readonly', 'Read Only'), ('member', 'Member Portal')], default='readonly', max_length=20),
        ),
    ]
