# Generated by Django 6.0.3 on 2026-03-24 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('late', 'Late Arrival'), ('absent', 'Absent Without Notice'), ('misconduct', 'Misconduct'), ('phone', 'Phone Disruption'), ('other', 'Other')], default='late', max_length=30)),
                ('description', models.CharField(blank=True, help_text='Optional extra detail', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='meetings.meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]

    # The table was already created by a prior migration run with a different
    # Python interpreter. Wrap the operation so it skips gracefully if the
    # table already exists.
    def apply(self, project_state, schema_editor, collect_sql=False):
        from django.db import connection
        existing = connection.introspection.table_names()
        if 'meetings_meetingpenalty' in existing:
            # Table exists — just update the state, skip DDL
            new_state = project_state.clone()
            for operation in self.operations:
                operation.state_forwards(self.app_label, new_state)
            return new_state
        return super().apply(project_state, schema_editor, collect_sql)
