# Generated by Django 6.0.2 on 2026-03-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meetingpenalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingpenalty',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount collected', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='meetingpenalty',
            name='paid_ref',
            field=models.CharField(blank=True, help_text='M-Pesa code, receipt, or other reference', max_length=100),
        ),
    ]
