# Generated by Django 6.0.3 on 2026-03-23 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_taken', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Fully Paid'), ('defaulted', 'Defaulted')], default='active', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'ordering': ['-date_taken'],
            },
        ),
    ]
