# Generated by Django 6.0.3 on 2026-03-23 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_loan_interest_percent_loan_due_date_and_more'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_loans', to='members.member', verbose_name='Guarantor'),
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('document', models.FileField(blank=True, null=True, upload_to='collateral_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='loans.loan')),
            ],
        ),
    ]
