# Generated by Django 6.0.3 on 2026-03-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_loan_guarantor_loanguarantor'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('regular', 'Regular Loan'), ('emergency', 'Emergency Loan')], default='regular', max_length=20),
        ),
    ]
