# Generated by Django 6.0.2 on 2026-03-24 07:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loan_loan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('loan_type', models.CharField(choices=[('regular', 'Regular Loan'), ('emergency', 'Emergency Loan'), ('soft', 'Soft Loan')], default='regular', max_length=20)),
                ('interest_method', models.CharField(choices=[('reducing', 'Reducing Balance'), ('fixed', 'Fixed (Flat) Interest'), ('none', 'No Interest')], default='reducing', max_length=20)),
                ('interest_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Monthly interest rate (%)', max_digits=5)),
                ('max_duration_months', models.PositiveIntegerField(default=12, help_text='Maximum repayment period (months)')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for no limit', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Loan product / settings to apply', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loanproduct'),
        ),
    ]
