# Generated by Django 6.0.2 on 2026-03-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loanproduct_alter_loan_loan_type_loan_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='max_amount_basis',
            field=models.CharField(choices=[('fixed', 'Fixed Amount (manual KES limit)'), ('contributions', "Member's Total Contributions"), ('none', 'No Limit')], default='none', help_text='How the maximum loan amount is determined', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Used only when basis is "Fixed Amount"', max_digits=12, null=True),
        ),
    ]
