# Generated by Django 5.0.14 on 2026-03-31 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loanproduct_max_amount_basis_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='chama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_products', to='tenants.chama'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='max_amount_basis',
            field=models.CharField(choices=[('fixed', 'Fixed Amount (manual KES limit)'), ('contributions', "Member's Total Contributions"), ('shares', "Member's Share Capital × Multiplier"), ('none', 'No Limit')], default='none', help_text='How the maximum loan amount is determined', max_length=20),
        ),
    ]
