# Generated by Django 5.0.14 on 2026-04-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_loanproduct_chama_alter_loanproduct_max_amount_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_method',
            field=models.CharField(choices=[('reducing', 'Reducing Balance'), ('fixed', 'Fixed (Flat) Interest'), ('monthly_interest', 'Monthly Interest (accrues until paid)'), ('none', 'No Interest')], default='reducing', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='loan_type',
            field=models.CharField(choices=[('regular', 'Regular Loan'), ('emergency', 'Emergency Loan'), ('soft', 'Soft Loan'), ('monthly_interest', 'Monthly Interest Loan')], default='regular', max_length=20),
        ),
    ]
