# Generated by Django 4.2.30 on 2026-04-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_add_monthly_interest_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='loanproduct',
            constraint=models.UniqueConstraint(fields=('chama', 'name'), name='unique_loan_product_name_per_chama'),
        ),
    ]
