# Generated by Django 6.0.2 on 2026-03-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_deactivation_reason_member_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='exit_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('exited', 'Exited')], default='active', max_length=20),
        ),
    ]
