# Generated by Django 6.0.2 on 2026-03-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_exit_date_member_exit_notes_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='exit_settlement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount paid out (refund) or collected (debt) at exit', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='exit_settlement_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('waived', 'Waived / Written Off')], max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='exit_settlement_ref',
            field=models.CharField(blank=True, help_text='M-Pesa code, cheque number, or other reference', max_length=100),
        ),
    ]
