# Generated by Django 6.0.2 on 2026-03-24 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_exit_settlement_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
