# Generated by Django 5.0.14 on 2026-03-31 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_date_joined'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='chama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.chama'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
