# Generated by Django 5.0.14 on 2026-03-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_chama_alter_member_phone'),
        ('tenants', '0002_assign_default_chama'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('chama', 'phone'), name='unique_phone_per_chama'),
        ),
    ]
