# Generated by Django 4.2.30 on 2026-05-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_unique_phone_per_chama'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='member_ids/'),
        ),
        migrations.AddField(
            model_name='member',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='member_ids/'),
        ),
        migrations.AddField(
            model_name='member',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='next_of_kin_relation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='member_photos/'),
        ),
    ]
