# Generated by Django 4.2.30 on 2026-05-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_id_back_member_id_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='reg_payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='reg_payment_reference',
            field=models.CharField(blank=True, help_text='M-Pesa code, receipt no., etc.', max_length=100),
        ),
    ]
