# Generated by Django 4.2.13 on 2026-06-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_member_reg_payment_mode_member_reg_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID or Passport number', max_length=30),
        ),
    ]
