# Generated by Django 6.0.2 on 2026-03-24 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_member_exit_date_member_exit_notes_member_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(blank=True, help_text='e.g. Meeting, Stationery, Bank', max_length=100)),
                ('receipt_no', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('contribution', 'Member Contribution'), ('registration', 'Registration Fee'), ('loan_issued', 'Loan Disbursed'), ('loan_repayment', 'Loan Repayment'), ('interest', 'Interest Received'), ('penalty', 'Penalty Collected'), ('expense', 'Expense'), ('other', 'Other')], max_length=30)),
                ('direction', models.CharField(choices=[('credit', 'Credit (In)'), ('debit', 'Debit (Out)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, help_text='e.g. Loan #5, Contribution #12', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_manual', models.BooleanField(default=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='members.member')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
