# Generated by Django 5.0.14 on 2026-03-31 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_expense_is_voided_expense_void_reason'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='chama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tenants.chama'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='chama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tenants.chama'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('contribution', 'Member Contribution'), ('registration', 'Registration Fee'), ('loan_issued', 'Loan Disbursed'), ('loan_repayment', 'Loan Repayment'), ('interest', 'Interest Received'), ('penalty', 'Penalty Collected'), ('expense', 'Expense'), ('share_capital', 'Share Capital'), ('other', 'Other')], max_length=30),
        ),
    ]
