# Generated by Django 4.2.30 on 2026-04-26 14:32

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0007_member_unique_phone_per_chama'),
        ('tenants', '0005_add_payment_request'),
        ('accounting', '0003_expense_chama_transaction_chama_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearEndPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Financial year e.g. 2025')),
                ('payout_date', models.DateField()),
                ('total_contributions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_income_pool', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_distributed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_end_payouts', to='tenants.chama')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_end_payouts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-payout_date'],
                'unique_together': {('chama', 'year')},
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('contribution', 'Member Contribution'), ('registration', 'Registration Fee'), ('loan_issued', 'Loan Disbursed'), ('loan_repayment', 'Loan Repayment'), ('interest', 'Interest Received'), ('penalty', 'Penalty Collected'), ('expense', 'Expense'), ('share_capital', 'Share Capital'), ('other', 'Other'), ('welfare_contribution', 'Welfare Contribution'), ('welfare_disbursement', 'Welfare Disbursement'), ('investment_capital', 'Investment Capital'), ('investment_income', 'Investment Income'), ('investment_expense', 'Investment Expense')], max_length=30),
        ),
        migrations.CreateModel(
            name='YearEndPayoutLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('profit_share', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('penalty_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('net_payout', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer')], default='mpesa', max_length=20)),
                ('payment_ref', models.CharField(blank=True, max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_end_payout_lines', to='members.member')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.yearendpayout')),
            ],
            options={
                'ordering': ['member__name'],
                'unique_together': {('payout', 'member')},
            },
        ),
    ]
