# Generated by Django 4.2.30 on 2026-05-18 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_add_payment_request'),
        ('accounting', '0004_year_end_payout'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('bank_interest', 'Bank Interest'), ('dividend', 'Dividend / Investment Return'), ('grant', 'Grant'), ('donation', 'Donation'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, help_text='Bank slip, receipt no., etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_incomes', to='tenants.chama')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
