# Generated by Django 5.2.15 on 2026-06-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_otherincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='fund_source',
            field=models.CharField(choices=[('contributions', 'Contributions Fund'), ('registration', 'Registration Fees'), ('outside', 'Outside Source (Donor/Other)')], default='contributions', help_text='Which fund is this expense paid from?', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('contribution', 'Member Contribution'), ('registration', 'Registration Fee'), ('loan_issued', 'Loan Disbursed'), ('loan_repayment', 'Loan Repayment'), ('interest', 'Interest Received'), ('penalty', 'Penalty Collected'), ('expense', 'Expense'), ('share_capital', 'Share Capital'), ('other', 'Other')], max_length=30),
        ),
    ]
