# Generated by Django 5.2.15 on 2026-06-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_add_expense_fund_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='fund_source',
            field=models.CharField(choices=[('contributions', 'Contributions Fund'), ('registration', 'Registration Fees'), ('other_income', 'Other Income (Bank Interest / Dividends)'), ('outside', 'Outside Source (Donor / Not from chama funds)')], default='contributions', help_text='Which fund is this expense paid from?', max_length=20),
        ),
    ]
